# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c08f42ba43224b6c5619a66bc8c91c43db8b6e209c8d7ea4a8410d4ebc5a04ec25ebafbddf076b1622fbc86e1cd8e6f882603b1d7fe2924a02ebcb34d249622

test:
  secret_key_base: 2bd20b35697df28866b018bf3555b53fd91282d5a75ea3cb2368dcb20737378aeb16c07d1f90f7cfdbbc7490fc9e00744814b2901e49c47cc9501ee5b1d6f69d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
